# Generated by Django 2.1.5 on 2019-02-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_remove_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
            ],
        ),
    ]
