# Generated by Django 2.1.5 on 2019-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_courttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_day', models.CharField(max_length=120, verbose_name='Event Date')),
                ('event_time', models.TimeField(verbose_name='Event Time')),
            ],
        ),
        migrations.DeleteModel(
            name='CourtTable',
        ),
    ]
